### ISSUE TITLE
wrap up age data into formula for lookup

### ISSUE THREAD

**Issue by willbutler42** [gadget-framework/gadget3#91] opened 2022-11-22 10:44 UTC
It would be useful to be able to wrap up age data into a lookup table, for instance, if parameter values vary within ages. Does something for this exist? If not, g3_timeareadata could be modified or a new function added (something like [0b7ac93](https://github.com/gadget-framework/gadgetutils/commit/0b7ac935e6dc81650f146bfcb56fe55e91e4af4e))?

**Comment by lentinj** [comment] 2022-11-22 11:06
I think this is a duplicate of #22? Or is there some other subtlety you're after?

We have the gubbins required as part of ``g3_param_table`` to look for arbitrary columns, we just don't use them here. At least not yet. Ideally the 2 kinda-similar mechanisms would combine, but it's surprisingly hard to achieve atm.

**Closed by lentinj** 2022-11-22 11:06 UTC

**Comment by willbutler42** [comment] 2022-11-22 11:25
Yes, it's a duplicate, no other subtleties!
